version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-backend
        container_name: laravel-backend
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./vendor:/var/www/html/vendor
            - ./storage:/var/www/html/storage
        expose:
            - "9000"
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=hotel_backend
            - DB_USERNAME=postgres
            - DB_PASSWORD=your_postgres_password
        depends_on:
            - db

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: postgres:15
        container_name: postgres-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: hotel_backend
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: your_postgres_password
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
