name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres   # Superuser (default)
          POSTGRES_PASSWORD: sami   # Your password
          POSTGRES_DB: hotel_backend  # Your DB name
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_CONNECTION: pgsql
      DB_HOST: postgres  # Matches the service name
      DB_PORT: 5432
      DB_DATABASE: hotel_backend
      DB_USERNAME: postgres  # User = postgres
      DB_PASSWORD: sami     # Password = sami
      APP_ENV: testing
      APP_KEY: ${{ secrets.APP_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pgsql, pdo, pdo_pgsql
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate app key
        run: php artisan key:generate --force

      - name: Wait for PostgreSQL (5s)
        run: sleep 5  # Ensures DB is ready

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test